CONNECT TO SWARE_L
;

CREATE TABLE HIP.HIP_FINDING_CACHE_SET (
  cache_set_id            integer generated by default AS IDENTITY (  
                                  START WITH +1 INCREMENT BY +1 ),
  cache_set_status        varchar(8) not null,
  search_param_hash       bigint not null,
  in_cycle                char(1) not null,
  created_by              varchar(20) not null,
  created_at              timestamp not null,
  row_count               integer not null,
  org_l1_id               integer not null,
  org_id                  integer not null
  )
  INDEX IN "TS_INDEX1_4K" NOT LOGGED INITIALLY
;
  
ALTER TABLE HIP.HIP_FINDING_CACHE_SET
  ADD CONSTRAINT hip_finding_cache_set_PK PRIMARY KEY (cache_set_id)
  ADD CONSTRAINT hip_finding_cache_set_ck1 CHECK ( cache_set_status IN ('valid','invalid', 'building'))
  ADD CONSTRAINT hip_finding_cache_set_ck2 CHECK ( in_cycle IN ('y', 'n'))
;

CREATE TABLE HIP.HIP_FINDING_CACHE_ELEMENT  (
  cache_set_id            integer not null,
  row_num                 bigint not null,
  scan_id                 integer not null,
--  finding_id              integer not null,
  finding_vid             integer not null,
  asset_vid               integer not null,
  publish_ready_timestamp timestamp,
  group_name              varchar(80),
  hc_group_id             integer,
  suppress_timestamp      timestamp,
  suppress_id             integer,
  valid_finding_flag      char(1) not null,
  day_of_week             smallint not null
  )   
  INDEX IN "TS_INDEX1_4K" NOT LOGGED INITIALLY
--  PARTITION BY RANGE(???) (
--  )
; 

ALTER TABLE HIP.HIP_FINDING_CACHE_ELEMENT
  ADD CONSTRAINT hip_finding_cache_element_pk PRIMARY KEY (cache_set_id, row_num)
  ADD CONSTRAINT hip_finding_cache_element_fk1 FOREIGN KEY (cache_set_id) REFERENCES
    hip.hip_finding_cache_set (cache_set_id)
  ADD CONSTRAINT hip_finding_cache_element_ck1 CHECK ( valid_finding_flag IN ('y', 'n'))
;

create view hip.hip_finding_cache_set_v as select * from hip.hip_finding_cache_set
;

create view hip.hip_finding_cache_element_v as select * from hip.hip_finding_cache_element
;

-- Remember Grants

disconnect sware_l
;