CONNECT TO SWARE_L}

CREATE BUFFERPOOL BP_4K IMMEDIATE SIZE 250 PAGESIZE 4K}
CREATE BUFFERPOOL BP_32K IMMEDIATE SIZE 250 PAGESIZE 32K}

CREATE REGULAR TABLESPACE TS_INDEX1_4K
	PAGESIZE 4 K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 12.67 PREFETCHSIZE 16 TRANSFERRATE 0.18 BUFFERPOOL BP_4K
	DROPPED TABLE RECOVERY ON}

CREATE REGULAR TABLESPACE TS_DIM1_32K
	PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 12.67 PREFETCHSIZE 16 TRANSFERRATE 0.18 BUFFERPOOL BP_32K
	DROPPED TABLE RECOVERY ON}

CREATE REGULAR TABLESPACE TS_FACT1_32K
	PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 12.67 PREFETCHSIZE 16 TRANSFERRATE 0.18 BUFFERPOOL BP_32K
	DROPPED TABLE RECOVERY ON}

CREATE REGULAR TABLESPACE TS_SUM1_32K
	PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 12.67 PREFETCHSIZE 16 TRANSFERRATE 0.18 BUFFERPOOL BP_32K
	DROPPED TABLE RECOVERY ON}

CREATE REGULAR TABLESPACE TS_USERSPACE1_32K
	PAGESIZE 32 K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 12.67 PREFETCHSIZE 16 TRANSFERRATE 0.18 BUFFERPOOL BP_32K
	DROPPED TABLE RECOVERY ON}

CREATE USER TEMPORARY TABLESPACE TS_USER1_32K
  PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE EXTENTSIZE 16 OVERHEAD 12.67 PREFETCHSIZE 16 TRANSFERRATE 0.18 BUFFERPOOL BP_32K}


-- UPDATE TRANSACTION LOG SIZE
--UPDATE DB CFG FOR SWARE_L USING logarchmeth1 OFF logarchmeth2 OFF logprimary 13 logsecond 10 logfilsiz 32000}
-- GRANT HIP USER ACCESS
GRANT  DBADM ON DATABASE  TO USER HIP}
